"use client";

import {
  Activity,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Banknote,
  Bell,
  BookOpen,
  Bot,
  BriefcaseBusiness,
  Calculator,
  CalendarClock,
  CalendarRange,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDot,
  CircleX,
  Clock,
  Copy,
  Cpu,
  CreditCard,
  Download,
  ExternalLink,
  File,
  FileCheck2,
  FileCode2,
  FileSpreadsheet,
  FileText,
  Filter,
  Fingerprint,
  Gauge,
  Github,
  Hash,
  Inbox,
  Info,
  Landmark,
  Languages,
  Layers,
  Link2,
  Loader2,
  Lock,
  Mail,
  Package,
  Pause,
  Play,
  PlayCircle,
  Plus,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scale,
  ScrollText,
  Search,
  SearchX,
  Send,
  Settings2,
  ShieldCheck,
  Sprout,
  Table2,
  Terminal,
  TrendingUp,
  TriangleAlert,
  Twitter,
  User,
  Users,
  Waves,
  Webhook,
  X,
  Youtube,
  Zap,
  type LucideProps,
} from "lucide-react";

type IconProps = {
  name: string;
  className?: string;
  strokeWidth?: number;
  size?: number;
};

const ICONS: Record<string, React.ComponentType<LucideProps>> = {
  activity: Activity,
  "arrow-down-left": ArrowDownLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "at-sign": AtSign,
  banknote: Banknote,
  bell: Bell,
  "book-open": BookOpen,
  bot: Bot,
  "briefcase-business": BriefcaseBusiness,
  calculator: Calculator,
  "calendar-clock": CalendarClock,
  "calendar-range": CalendarRange,
  check: Check,
  "check-circle-2": CircleCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-dot": CircleDot,
  clock: Clock,
  copy: Copy,
  cpu: Cpu,
  "credit-card": CreditCard,
  download: Download,
  "external-link": ExternalLink,
  file: File,
  "file-check-2": FileCheck2,
  "file-code-2": FileCode2,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  filter: Filter,
  fingerprint: Fingerprint,
  gauge: Gauge,
  github: Github,
  hash: Hash,
  inbox: Inbox,
  info: Info,
  landmark: Landmark,
  languages: Languages,
  layers: Layers,
  link: Link2,
  "loader-2": Loader2,
  lock: Lock,
  mail: Mail,
  package: Package,
  pause: Pause,
  play: Play,
  "play-circle": PlayCircle,
  plus: Plus,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  "search-x": SearchX,
  send: Send,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  sprout: Sprout,
  "table-2": Table2,
  terminal: Terminal,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  twitter: Twitter,
  user: User,
  users: Users,
  waves: Waves,
  webhook: Webhook,
  x: X,
  "x-circle": CircleX,
  youtube: Youtube,
  zap: Zap,
};

export function Icon({ name, className = "", strokeWidth = 1.5, size = 16 }: IconProps) {
  const LucideIcon = ICONS[name] ?? Circle;

  return (
    <span className={`inline-flex items-center justify-center ${className}`} aria-hidden="true">
      <LucideIcon size={size} strokeWidth={strokeWidth} />
    </span>
  );
}
